// Copyright (C) 2019-2022 Chrystian Huot <chrystian.huot@saubeo.solutions>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>

package main

import (
	"fmt"
	"os"
	"strings"
)

// The plugin API reference, written by the server itself.
//
// A review of the hand-written documentation found six capabilities that worked
// but were documented nowhere, three that existed but were never mentioned, and
// one documented in detail that did nothing at all. That is what two parallel
// lists maintained by hand always become.
//
// So the reference is emitted from the same declarations the code runs on: the
// point catalogue in plugin_points.go and the model catalogue in
// plugin_models.go. Adding a point or a model documents it. Removing one
// removes its documentation. The two cannot disagree, because there is only one
// of them.
//
// Run with -plugin_docs <file> to write it.

func writePluginDocs(path string) error {
	var b strings.Builder

	b.WriteString("# Plugin API reference\n\n")
	b.WriteString(fmt.Sprintf(
		"Generated by Rdio Scanner %s. Do not edit — run `rdio-scanner -plugin_docs` to regenerate.\n\n",
		Version,
	))
	b.WriteString(fmt.Sprintf("Plugin API version: **%d**\n\n", CurrentPluginApiVersion))
	b.WriteString("A plugin declares `\"apiVersion\": " + fmt.Sprint(CurrentPluginApiVersion) +
		"` in its manifest. The server refuses a plugin written for a newer API than it\n" +
		"knows, and supports one version back — so a plugin keeps working across server\n" +
		"updates without being rebuilt.\n\n")

	writeVerbsSection(&b)
	writeCapabilitiesSection(&b)
	writePointsSection(&b)
	writeModelsSection(&b)

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// pluginCapabilities describes each top-level rdio.* namespace.
//
// Unlike points and models these cannot be derived — a Go closure bound into a
// runtime does not carry its JavaScript signature — so this is written by hand.
// What stops it drifting is TestEveryCapabilityIsDocumented, which reads the
// bindings out of plugin_api.go and fails if one is missing here. That is the
// check that would have caught the six capabilities the review found working
// but documented nowhere.
var pluginCapabilities = []struct {
	name    string
	summary string
	methods []string
}{
	{"plugin", "Identity and directories.", []string{
		"id", "version", "dir — where this plugin's files live", "dataDir — storage that survives updates",
	}},
	{"log", "Write to the server log. Appears under the Plugins category.", []string{
		"rdio.log(level, message)", "console.log / warn / error",
	}},
	{"config", "This plugin's settings, and values published to the webapp.", []string{
		"get(key)", "getAll()", "set(key, value)", "expose(key, value)",
	}},
	{"db", "SQL against any table in the database, core's included.", []string{
		"query(sql, args)", "exec(sql, args)", "queryAsync(sql, args)", "execAsync(sql, args)",
	}},
	{"models", "Read and write the server's configuration. See below.", nil},
	{"calls", "Read calls and audio, and publish fields onto them.", []string{
		"get(id, {audio})", "search(options)", "findId(system, talkgroup, dateTime)",
		"update(id, fields)", "extendField(spec)",
	}},
	{"search", "Make one of your columns findable through the normal call search.", []string{
		"extend(spec)",
	}},
	{"systems", "The configured systems and talkgroups.", []string{"list()"}},
	{"fs", "The filesystem. Relative paths resolve inside this plugin's data directory.", []string{
		"readFile(path)", "readText(path)", "writeFile(path, data)", "appendFile(path, data)",
		"exists(path)", "stat(path)", "list(path)", "mkdir(path)", "remove(path)",
		"rename(from, to)", "resolve(path)", "tempDir()",
	}},
	{"exec", "Run a program. Returns a promise with its exit code and output.", []string{
		"rdio.exec(name, args, options)",
	}},
	{"crypto", "Hashing and encoding, which JavaScript does not provide.", []string{
		"hash(algorithm, data)", "hmac(algorithm, key, data)",
		"base64Encode(data)", "base64Decode(text)", "hexEncode(data)", "hexDecode(text)",
		"randomBytes(n)", "uuid()",
	}},
	{"http", "Outbound requests, including multipart uploads.", []string{
		"request(options)", "multipart(options)",
	}},
	{"routes", "Serve HTTP endpoints.", []string{
		"register(method, path, handler)", "registerAbsolute(path, handler)",
	}},
	{"ws", "Your own websocket commands, over the connection clients already have.", []string{
		"on(command, handler)", "emit(filter, command, payload)",
	}},
	{"apikeys", "Validate an API key someone handed you.", []string{"verify(key, system, talkgroup)"}},
	{"admin", "Validate an admin session token.", []string{"verifyToken(token)"}},
	{"downstreams", "Forward to downstream servers without handling their keys.", []string{"forward(spec)"}},
	{"capabilities", "Advertise a feature to peer servers via /api/capabilities.", []string{"advertise(name)"}},
	{"schedule", "Run something on an interval.", []string{"rdio.schedule(intervalMs, fn)"}},
	{"definePoint", "Publish an extension point of your own.", []string{"rdio.definePoint(name)"}},
	{"on", "Observe an extension point.", nil},
	{"filter", "Modify or veto at an extension point.", nil},
	{"override", "Replace the server's behaviour at an extension point.", nil},
	{"provide", "Supply something the server does not have.", nil},
}

func writeCapabilitiesSection(b *strings.Builder) {
	b.WriteString("## What a plugin can reach\n\n")
	b.WriteString("Nothing here is gated. A plugin does what it does, and the decision about\n")
	b.WriteString("whether to trust it happens once, at install.\n\n")

	for _, capability := range pluginCapabilities {
		if len(capability.methods) == 0 {
			continue
		}

		b.WriteString("### `rdio." + capability.name + "`\n\n")
		b.WriteString(capability.summary + "\n\n")

		for _, method := range capability.methods {
			b.WriteString("- `" + method + "`\n")
		}
		b.WriteString("\n")
	}
}

func writeVerbsSection(b *strings.Builder) {
	b.WriteString("## The four verbs\n\n")
	b.WriteString("Everything a plugin does to the server is one of these, registered against a\n")
	b.WriteString("named extension point.\n\n")
	b.WriteString("| Verb | Meaning |\n|---|---|\n")
	b.WriteString("| `rdio.on(point, fn)` | Observe. Runs asynchronously and cannot change anything. |\n")
	b.WriteString("| `rdio.filter(point, fn)` | Modify what passes through, or veto it by returning `{drop: true}`. |\n")
	b.WriteString("| `rdio.override(point, fn)` | Replace the server's behaviour for that point entirely. |\n")
	b.WriteString("| `rdio.provide(point, fn)` | Supply something the server does not have. First answer wins. |\n\n")

	b.WriteString("`rdio.definePoint(name)` publishes a point of your own, so other plugins can\n")
	b.WriteString("extend yours.\n\n")

	b.WriteString("Registering against a point that does not exist is an error, rather than a\n")
	b.WriteString("handler that silently never runs.\n\n")

	b.WriteString("A `filter` or `provide` handler that times out, throws, or returns something\n")
	b.WriteString("unusable is treated as having done nothing, and whatever it was given passes\n")
	b.WriteString("through unchanged. `override` is the exception: replacing behaviour means\n")
	b.WriteString("owning its failures, because there is no original left to fall back to.\n\n")
}

func writePointsSection(b *strings.Builder) {
	b.WriteString("## Extension points\n\n")

	groups := []struct {
		title  string
		points []string
	}{
		{"Lifecycle", []string{
			PointStartup, PointShutdown, PointTick, PointConfigChanged,
			PointClientConnect, PointClientDisconnect,
		}},
		{"Ingest", []string{
			PointCallReceive, PointCallAccept, PointCallDuplicate,
			PointCallConvert, PointCallStore, PointCallStored,
		}},
		{"Delivery", []string{
			PointCallDelay, PointCallEmit, PointCallPayload, PointCallEmitted,
			PointDownstreamSend, PointClientConfig,
		}},
		{"Access", []string{
			PointAccessCheck, PointAccessScope, PointApikeyCheck, PointAdminCheck,
		}},
		{"Data", []string{
			PointCallSearch, PointCallPrune, PointCallAudio, PointConfigSave,
		}},
	}

	for _, group := range groups {
		b.WriteString("### " + group.title + "\n\n")
		b.WriteString("| Point | Timeout | Notes |\n|---|---|---|\n")

		for _, point := range group.points {
			timeout := "default"
			if custom, ok := pointTimeouts[point]; ok {
				timeout = custom.String()
			}

			note := pointNotes[point]
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", point, timeout, note))
		}

		b.WriteString("\n")
	}
}

func writeModelsSection(b *strings.Builder) {
	b.WriteString("## Configuration models\n\n")
	b.WriteString("`rdio.models.<name>` reads and writes the server's configuration. Each one\n")
	b.WriteString("offers `list()`, `get(id)`, `set(entry)` and `remove(id)`. Entries are the same\n")
	b.WriteString("shape the admin panel uses.\n\n")

	for i := range pluginModels {
		model := &pluginModels[i]

		b.WriteString("### `rdio.models." + model.name + "`\n\n")
		b.WriteString(model.summary + "\n\n")

		fields := modelFields(model.sample)
		if len(fields) == 0 {
			continue
		}

		b.WriteString("Fields: ")
		for j, field := range fields {
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString("`" + field + "`")
		}
		b.WriteString("\n\nIdentified by `" + model.key + "`.\n\n")
	}
}

// pointNotes is the one hand-written part, because what a point *means* is not
// derivable from its name. Anything missing here shows as a blank cell rather
// than a wrong description.
var pointNotes = map[string]string{
	PointStartup:          "After the plugin loads and its tables exist.",
	PointShutdown:         "The server is stopping. Best effort.",
	PointTick:             "Hourly, alongside the built-in maintenance run.",
	PointConfigChanged:    "This plugin's settings were saved.",
	PointClientConnect:    "A listener connected.",
	PointClientDisconnect: "A listener disconnected.",

	PointCallReceive:   "A call arrived, before anything has been decided about it.",
	PointCallAccept:    "Whether to accept the call at all. Veto to discard it.",
	PointCallDuplicate: "Whether the call is a duplicate of one already stored.",
	PointCallConvert:   "Audio conversion. Override to replace ffmpeg entirely.",
	PointCallStore:     "Last chance before storage: modify, replace the audio, or drop.",
	PointCallStored:    "The call has an id. Where most work belongs.",

	PointCallDelay:      "How long to hold the call before listeners see it.",
	PointCallEmit:       "Per listener, before delivery. Redact or withhold.",
	PointCallPayload:    "The JSON shape a client receives.",
	PointCallEmitted:    "The call has been sent to listeners.",
	PointDownstreamSend: "Per downstream, before forwarding.",
	PointClientConfig:   "The configuration payload each client receives.",

	PointAccessCheck: "Validate an access code. Provide to authenticate elsewhere.",
	PointAccessScope: "What systems and talkgroups a session may see.",
	PointApikeyCheck: "Validate an API key used for uploads.",
	PointAdminCheck:  "Validate an admin session.",

	PointCallSearch: "Search predicates and results.",
	PointCallPrune:  "Whether a call may be deleted by retention.",
	PointCallAudio:  "Supply a call's audio when the server has none stored.",
	PointConfigSave: "Configuration is being saved.",
}
