// Copyright (C) 2019-2022 Chrystian Huot <chrystian.huot@saubeo.solutions>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>

package main

import (
	"fmt"
	"os"
	"strings"
)

// The plugin API reference, written by the server itself.
//
// A review of the hand-written documentation found six capabilities that worked
// but were documented nowhere, three that existed but were never mentioned, and
// one documented in detail that did nothing at all. That is what two parallel
// lists maintained by hand always become.
//
// So the reference is emitted from the same declarations the code runs on: the
// point catalogue in plugin_points.go and the model catalogue in
// plugin_models.go. Adding a point or a model documents it. Removing one
// removes its documentation. The two cannot disagree, because there is only one
// of them.
//
// Run with -plugin_docs <file> to write it.

func writePluginDocs(path string) error {
	var b strings.Builder

	b.WriteString("# Plugin API reference\n\n")
	b.WriteString(fmt.Sprintf(
		"Generated by Rdio Scanner %s. Do not edit — run `rdio-scanner -plugin_docs` to regenerate.\n\n",
		Version,
	))
	b.WriteString(fmt.Sprintf("Plugin API version: **%d**\n\n", CurrentPluginApiVersion))
	b.WriteString("A plugin declares `\"apiVersion\": " + fmt.Sprint(CurrentPluginApiVersion) +
		"` in its manifest. The server refuses a plugin written for a newer API than it\n" +
		"knows, and supports one version back — so a plugin keeps working across server\n" +
		"updates without being rebuilt.\n\n")

	writeVerbsSection(&b)
	writeCapabilitiesSection(&b)
	writePointsSection(&b)
	writeModelsSection(&b)

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// pluginCapabilities describes each top-level rdio.* namespace.
//
// Unlike points and models these cannot be derived — a Go closure bound into a
// runtime does not carry its JavaScript signature — so this is written by hand.
// What stops it drifting is TestEveryCapabilityIsDocumented, which reads the
// bindings out of plugin_api.go and fails if one is missing here. That is the
// check that would have caught the six capabilities the review found working
// but documented nowhere.
var pluginCapabilities = []struct {
	name    string
	summary string
	methods []string
}{
	{"plugin", "Identity and directories.", []string{
		"id", "version", "dir — where this plugin's files live", "dataDir — storage that survives updates",
	}},
	{"server", "What this plugin is running inside.", []string{
		"version — the running rdio version",
		"apiVersion — the plugin API version this server implements",
	}},
	{"log", "Write to the server log. Appears under the Plugins category.", []string{
		"rdio.log(level, message)", "console.log / warn / error",
	}},
	{"config", "This plugin's settings, and values published to the webapp.", []string{
		"get(key)", "getAll()", "set(key, value)", "expose(key, value)",
	}},
	{"db", "SQL against any table in the database, core's included.", []string{
		"query(sql, args)", "exec(sql, args)", "queryAsync(sql, args)", "execAsync(sql, args)",
	}},
	{"models", "Read and write the server's configuration. See below.", nil},
	{"calls", "Read calls and audio, publish fields onto them, and create new ones.", []string{
		"get(id, {audio})", "search(options)", "findId(system, talkgroup, dateTime)",
		"update(id, fields)", "extendField(spec)",
		"create({system, talkgroup, audio, dateTime, audioName, audioType, meta}) — goes in the same door an upload does, so blacklists, duplicate detection, conversion and every extension point apply",
	}},
	{"plugins", "Call and be called by other plugins, and broadcast events between them.", []string{
		"list()", "has(id)",
		"handle(method, fn) — offer a method others may call",
		"call(pluginId, method, args) — returns a promise; a call into a plugin already waiting on someone else is refused rather than deadlocked",
		"publish(topic, payload) — returns how many received it; never waits",
		"subscribe(topic, fn)",
	}},
	{"search", "Make one of your columns findable through the normal call search.", []string{
		"extend(spec)",
	}},
	{"systems", "The configured systems and talkgroups.", []string{"list()"}},
	{"fs", "The filesystem. Relative paths resolve inside this plugin's data directory.", []string{
		"readFile(path)", "readText(path)", "writeFile(path, data)", "appendFile(path, data)",
		"exists(path)", "stat(path)", "list(path)", "mkdir(path)", "remove(path)",
		"rename(from, to)", "resolve(path)", "tempDir()",
	}},
	{"exec", "Run a program. Returns a promise with its exit code and output.", []string{
		"rdio.exec(name, args, options)",
	}},
	{"crypto", "Hashing and encoding, which JavaScript does not provide.", []string{
		"hash(algorithm, data)", "hmac(algorithm, key, data)",
		"base64Encode(data)", "base64Decode(text)", "hexEncode(data)", "hexDecode(text)",
		"randomBytes(n)", "uuid()",
	}},
	{"audio", "Decode, analyse and re-encode call audio. Needs ffmpeg installed.", []string{
		"probe(data) — duration, codec, sample rate, channels",
		"decode(data, {sampleRate, channels}) — 16-bit PCM as an Int16Array",
		"encode(samples, {sampleRate, channels, format})",
		"convert(data, {format, bitrate, sampleRate, normalize, filter})",
		"goertzel(samples, frequencies, {sampleRate, windowSize}) — energy per window, for tone detection",
	}},
	{"http", "Outbound requests, including multipart uploads.", []string{
		"request(options)", "multipart(options)",
	}},
	{"routes", "Serve HTTP endpoints.", []string{
		"register(method, path, handler)", "registerAbsolute(path, handler)",
	}},
	{"ws", "Your own websocket commands, over the connection clients already have.", []string{
		"on(command, handler)", "emit(filter, command, payload)",
	}},
	{"apikeys", "Validate an API key someone handed you.", []string{"verify(key, system, talkgroup)"}},
	{"admin", "Validate an admin session token.", []string{"verifyToken(token)"}},
	{"downstreams", "Forward to downstream servers without handling their keys.", []string{"forward(spec)"}},
	{"capabilities", "Advertise a feature to peer servers via /api/capabilities.", []string{"advertise(name)"}},
	{"schedule", "Run something on an interval.", []string{"rdio.schedule(intervalMs, fn)"}},
	{"definePoint", "Publish an extension point of your own.", []string{"rdio.definePoint(name)"}},
	{"on", "Observe an extension point.", nil},
	{"filter", "Modify or veto at an extension point.", nil},
	{"override", "Replace the server's behaviour at an extension point.", nil},
	{"provide", "Supply something the server does not have.", nil},
}

func writeCapabilitiesSection(b *strings.Builder) {
	b.WriteString("## What a plugin can reach\n\n")
	b.WriteString("Nothing here is gated. A plugin does what it does, and the decision about\n")
	b.WriteString("whether to trust it happens once, at install.\n\n")

	for _, capability := range pluginCapabilities {
		if len(capability.methods) == 0 {
			continue
		}

		b.WriteString("### `rdio." + capability.name + "`\n\n")
		b.WriteString(capability.summary + "\n\n")

		for _, method := range capability.methods {
			b.WriteString("- `" + method + "`\n")
		}
		b.WriteString("\n")
	}
}

func writeVerbsSection(b *strings.Builder) {
	b.WriteString("## The four verbs\n\n")
	b.WriteString("Everything a plugin does to the server is one of these, registered against a\n")
	b.WriteString("named extension point.\n\n")
	b.WriteString("| Verb | Meaning |\n|---|---|\n")
	b.WriteString("| `rdio.on(point, fn)` | Observe. Runs asynchronously and cannot change anything. |\n")
	b.WriteString("| `rdio.filter(point, fn)` | Modify what passes through, or veto it by returning `{drop: true}`. |\n")
	b.WriteString("| `rdio.override(point, fn)` | Replace the server's behaviour for that point entirely. |\n")
	b.WriteString("| `rdio.provide(point, fn)` | Supply something the server does not have. First answer wins. |\n\n")

	b.WriteString("`rdio.definePoint(name)` publishes a point of your own, so other plugins can\n")
	b.WriteString("extend yours.\n\n")

	b.WriteString("Registering against a point that does not exist is an error, rather than a\n")
	b.WriteString("handler that silently never runs.\n\n")

	b.WriteString("A `filter` or `provide` handler that times out, throws, or returns something\n")
	b.WriteString("unusable is treated as having done nothing, and whatever it was given passes\n")
	b.WriteString("through unchanged. `override` is the exception: replacing behaviour means\n")
	b.WriteString("owning its failures, because there is no original left to fall back to.\n\n")
}

func writePointsSection(b *strings.Builder) {
	b.WriteString("## Extension points\n\n")

	groups := []struct {
		title  string
		points []string
	}{
		{"Lifecycle", []string{
			PointStartup, PointShutdown, PointTick, PointConfigChanged,
			PointClientConnect, PointClientDisconnect,
		}},
		{"Ingest", []string{
			PointCallReceive, PointCallAccept, PointCallDuplicate,
			PointCallConvert, PointCallStore, PointCallStored,
		}},
		{"Delivery", []string{
			PointCallDelay, PointCallEmit, PointCallPayload, PointCallEmitted,
			PointDownstreamSend, PointClientConfig,
		}},
		{"Access", []string{
			PointAccessCheck, PointAccessScope, PointApikeyCheck, PointAdminCheck,
		}},
		{"Data", []string{
			PointCallSearch, PointCallPrune, PointCallAudio, PointConfigSave,
		}},
	}

	for _, group := range groups {
		b.WriteString("### " + group.title + "\n\n")
		b.WriteString("| Point | Timeout | Notes |\n|---|---|---|\n")

		for _, point := range group.points {
			timeout := "default"
			if custom, ok := pointTimeouts[point]; ok {
				timeout = custom.String()
			}

			note := pointNotes[point]
			b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", point, timeout, note))
		}

		b.WriteString("\n")
	}
}

func writeModelsSection(b *strings.Builder) {
	b.WriteString("## Configuration models\n\n")
	b.WriteString("`rdio.models.<name>` reads and writes the server's configuration. Each one\n")
	b.WriteString("offers `list()`, `get(id)`, `set(entry)` and `remove(id)`. Entries are the same\n")
	b.WriteString("shape the admin panel uses.\n\n")

	for i := range pluginModels {
		model := &pluginModels[i]

		b.WriteString("### `rdio.models." + model.name + "`\n\n")
		b.WriteString(model.summary + "\n\n")

		fields := modelFields(model.sample)
		if len(fields) == 0 {
			continue
		}

		b.WriteString("Fields: ")
		for j, field := range fields {
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString("`" + field + "`")
		}
		b.WriteString("\n\nIdentified by `" + model.key + "`.\n\n")
	}
}

// pointNotes is the one hand-written part, because what a point *means* is not
// derivable from its name. Anything missing here shows as a blank cell rather
// than a wrong description.
var pointNotes = map[string]string{
	PointStartup:          "After the plugin loads and its tables exist. Fires per plugin, in load order, so this is the wrong place to ask what else is running — use `plugins.ready`.",
	PointPluginsReady:     "Once, after every plugin has started. Carries `count`. This is where a plugin that composes with another one wires up: `rdio.plugins.list()` and `has()` are only complete here, because `startup` fires while other plugins are still loading.",
	PointShutdown:         "The server is stopping. Best effort.",
	PointTick:             "Hourly, alongside the built-in maintenance run.",
	PointConfigChanged:    "This plugin's settings were saved.",
	PointClientConnect:    "A listener connected. Fires once the client is registered, which is after its first configuration has been sent — use `client.config` to change what that first payload contains.",
	PointClientDisconnect: "A listener disconnected.",

	PointCallReceive:   "A call arrived, before its system or talkgroup has been resolved. Carries audio. Rewrite `system` or `talkgroup` to reroute it, or return `{drop: true}` to discard it before any work is spent.",
	PointCallAccept:    "The call is fully resolved and passed the blacklists. Return `{drop: true}` to discard it. Metadata only, no audio.",
	PointCallDuplicate: "Fires only once rdio has already decided the call is a duplicate. Reads inverted from the others: returning nothing leaves the rejection standing, and only `{keep: true}` overrules it — so observing this point cannot accidentally disable duplicate detection.",
	PointCallConvert:   "Audio conversion. Override to replace ffmpeg entirely; return the new `audio`, and `audioType` if it changed. The only point with no fallback, so a failure here stores the call unconverted.",
	PointCallStore:     "Last chance before the write. Carries audio, so this is where processing that must be persisted belongs — normalisation, trimming, re-encoding — as well as a final `{drop: true}`.",
	PointCallStored:    "The call has an id. Where most work belongs.",

	PointCallDelay:      "How long to hold a call before listeners see it. Carries `delaySeconds`, what rdio's own per-system and per-talkgroup settings produced; return a different number to override it, or 0 to release the call at once. A veto here means \"do not hold it\", not \"do not send it\" — dropping is what the ingest points are for.",
	PointCallEmit:       "Runs once per listener per call, so it is the hottest point in the server and has a 250ms limit. The native access and livefeed checks have already passed by this point. Return `{drop: true}` to withhold the call from this listener alone. Carries a `client` describing the recipient.",
	PointCallPayload:    "The JSON a call is delivered as. Runs once per call rather than once per listener, because the payload is the same for everyone receiving it — use `rdio.ws` if you genuinely need to say something different to one client. Returned keys are merged as extra fields, so a plugin cannot remove the id or the audio and leave the webapp with a call it cannot play.",
	PointCallEmitted:    "A call finished going out to live listeners. Carries `recipients`, how many received it.",
	PointDownstreamSend: "Runs per downstream per call, before forwarding. Return `{drop: true}` to hold a call back from one downstream without affecting the others or the local listeners.",
	PointClientConfig:   "The configuration payload one client receives, in `config`. Runs on connect and on reconfiguration, not per call. This is where a theme ships its settings, and where anything varying by listener reaches the webapp. `groups`, `systems` and `tags` are restored if a result drops them, since a client without those has nothing to show and no way to say why.",

	PointAccessCheck: "A listener presented an access code. `provide` runs only when rdio's own table did not recognise it — return `{ident, systems}` to grant, nothing to refuse — so adding an auth plugin never invalidates the accounts already configured. `filter` always runs and may narrow the grant or refuse it with `{drop: true}`.",
	PointAccessScope: "What systems and talkgroups a session may see. Runs for every listener once, including on a server with no access codes at all, so it is the point for deciding visibility rather than admission. Return `{systems}` to narrow; `{drop: true}` shows the client nothing rather than disconnecting it.",
	PointApikeyCheck: "An upload presented an API key. Same shape as `access.check`: `provide` covers a key rdio has never seen, `filter` narrows or refuses one it has.",
	PointAdminCheck:  "An admin login. `provide` runs only when the local password check failed, so a plugin can add an external directory without ever being able to lock out the local password. `filter` runs on success, which is where a second factor or an address restriction goes. The submitted password is included, because an external directory cannot verify a credential it is not given; it is never logged.",

	PointCallSearch: "A search before it runs. Carries the query — `q`, `date`, `system`, `talkgroup`, `group`, `tag`, `limit`, `offset`, `sort` — and the `client` asking. Return any of those to narrow it, or `{drop: true}` for an empty result. Deliberately the query and not the results: filtering a page of calls would mean marshalling every row into the runtime on a path a user is waiting on. To contribute searchable data, use `rdio.search.extend`, which core resolves natively in the same SQL.",
	PointCallPrune:  "Retention, once an hour at most. Carries `days` and the `before` cutoff it implies. Return `{days: N}` to change how much is kept, or `{drop: true}` to skip this cycle — skipping is per cycle rather than a switch, so a plugin archiving calls does not have to remember to turn retention back on. Do the archiving on `rdio.schedule`, not here; a prune waiting on an upload would hold the scheduler for as long as it took.",
	PointCallAudio:  "`provide` a call's audio when the database no longer holds it. Only asked when the stored blob is empty, so an install keeping audio normally never reaches a plugin. Return the bytes, or `{audio, audioType, audioName}` if cold storage re-encoded them. This is what makes tiered retention possible: blank the column, keep the row, answer here.",
	PointConfigSave: "An admin configuration about to be written, in `config`. Observe it to notice that the systems a plugin mirrors have changed; filter it to refuse a configuration the plugin cannot work with, in which case nothing is written and the running configuration stays untouched.",
}
